Repository cms-kr/TZWi, pull requests merged in 2019-04, with the labels that each got.

#67 Fix error on 2017 MuonEG HLT
  TopAnalysis/data/combineHLT/ttbarDoubleLepton/2017.yaml
Labels: postprocessor

#68 Steps for parallel-input
  TopAnalysis/python/postprocessing/CopyBranch.py
  TopAnalysis/test/fcncTriLepton/01_prod_ntuple.sh
Labels: postprocessor

#69 Update datasets
  NanoAODProduction/data/datasets/NanoAOD/2016/RD.Run2016.yaml
  NanoAODProduction/data/datasets/NanoAOD/2017/RD.Run2017.yaml
  TopAnalysis/test/fcncTriLepton/01_prod_ntuple.sh
Labels: NanoAOD-production

#70 Update datasets
  NanoAODProduction/data/datasets/NanoAOD/2016/MC.RunIISummer16.central.yaml
  NanoAODProduction/data/datasets/NanoAOD/2016/MC.RunIISummer16.rareprocess.yaml
  NanoAODProduction/data/datasets/NanoAOD/2016/MC.RunIISummer16.syst.yaml
  NanoAODProduction/data/datasets/NanoAOD/2016/RD.Run2016.yaml
  NanoAODProduction/data/datasets/NanoAOD/2017/MC.RunIIFall17.central.yaml
  NanoAODProduction/data/datasets/NanoAOD/2017/RD.Run2017.yaml
  NanoAODProduction/scripts/tzwi-updatedataset
Labels: NanoAOD-production

#71 Change directory structure
  NanoAODProduction/data/datasets/NanoAOD/2017/MC.RunIIFall17.central.yaml
  NanoAODProduction/scripts/tzwi-updatedataset
  TopAnalysis/test/fcncTriLepton/01_prod_ntuple.sh
  TopAnalysis/test/ttbarDoubleLepton/01_prod_ntuple.sh
Labels: NanoAOD-production

#73 Save lepton1,2,3 in order of pt
  TopAnalysis/src/FCNCTriLeptonCppWorker.cc
Labels: postprocessor

#74 update datasets
  NanoAODProduction/data/datasets/NanoAOD/2016/MC.RunIISummer16.central.yaml
  NanoAODProduction/data/datasets/NanoAOD/2016/MC.RunIISummer16.syst.yaml
  NanoAODProduction/data/datasets/NanoAOD/2017/MC.RunIIFall17.central.yaml
  NanoAODProduction/data/datasets/NanoAOD/2017/MC.RunIIFall17.syst.yaml
Labels: NanoAOD-production

#77 bugfix typo
  TopAnalysis/test/ttbarDoubleLepton/02_make_histograms.py
Labels: bug

#80 typo from ntuple shell script
  TopAnalysis/data/histogramming/fcncTrilepton.yaml
  TopAnalysis/src/FCNCTriLeptonCppWorker.cc
  TopAnalysis/test/fcncTriLepton/01_prod_ntuple.sh
Labels: analysis, postprocessor

#83 Require grid proxy
  NanoAODProduction/scripts/tzwi-updatedataset
Labels: bug

#84 Simplify HLT information in the ntuple
  NanoAODProduction/data/datasets/NanoAOD/2016/MC.RunIISummer16.central.yaml
  TopAnalysis/data/combineHLT/fcncTriLepton/2016.yaml
  TopAnalysis/data/grouping/fcncTrilepton.yaml
  TopAnalysis/data/grouping/ttbbDilepton.yaml
  TopAnalysis/data/histogramming/fcncTrilepton.yaml
  TopAnalysis/python/postprocessing/fcncTriLeptonHLT.py
  TopAnalysis/python/postprocessing/ttbarDoubleLeptonHLT.py
  TopAnalysis/src/FCNCTriLeptonCppWorker.cc
  TopAnalysis/src/TTbarDoubleLeptonCppWorker.cc
  TopAnalysis/test/fcncTriLepton/01_prod_ntuple.sh
  TopAnalysis/test/ttbarDoubleLepton/01_prod_ntuple.sh
Labels: bug, postprocessor

#85 Adding GoodLeptonCode = -111 & change the Z and W candidated lepton
  TopAnalysis/src/FCNCTriLeptonCppWorker.cc
Labels: postprocessor

#86 Rearrange leptons by their charge pairing
  NanoAODProduction/data/datasets/NanoAOD/2016/MC.RunIISummer16.rareprocess.yaml
  TopAnalysis/interface/FCNCTriLeptonCppWorker.h
  TopAnalysis/src/FCNCTriLeptonCppWorker.cc
Labels: postprocessor
