Repository cms-kr/TZWi, pull requests merged in 2019-05, with the labels that each got.

#88 Use lumimask, copymode
  NanoAODProduction/data/branchsel.txt
  NanoAODProduction/data/lumi/Cert_271036-284044_13TeV_23Sep2016ReReco_Collisions16_JSON.txt
  NanoAODProduction/data/lumi/Cert_294927-306462_13TeV_EOY2017ReReco_Collisions17_JSON.txt
  NanoAODProduction/data/lumi/Cert_314472-325175_13TeV_17SeptEarlyReReco2018ABC_PromptEraD_Collisions18_JSON.txt
  TopAnalysis/python/postprocessing/ttbarDoubleLepton.py
  TopAnalysis/scripts/tzwi-makehistograms
  TopAnalysis/test/fcncTriLepton/01_prod_ntuple.sh
  TopAnalysis/test/ttbarDoubleLepton/01_prod_ntuple.sh
Labels: postprocessor

#89 bug in Z_charge and change the MODE naming in FCNCTrilepton
  TopAnalysis/python/postprocessing/fcncTriLepton.py
  TopAnalysis/python/postprocessing/fcncTriLeptonCutFlow.py
  TopAnalysis/src/FCNCTriLeptonCppWorker.cc
  TopAnalysis/test/fcncTriLepton/01_prod_ntuple.sh
Labels: bug, postprocessor

#91 2016 single leptron trigger
  TopAnalysis/data/combineHLT/ttbarDoubleLepton/2016.yaml
  TopAnalysis/interface/TTbarDoubleLeptonCppWorker.h
  TopAnalysis/src/TTbarDoubleLeptonCppWorker.cc
Labels: postprocessor

#92 use XRootD python module to select nearest SE
  NanoAODProduction/scripts/tzwi-updatedataset
Labels: tools

#93 bugfix keep file handle in xrood client
  NanoAODProduction/scripts/tzwi-updatedataset
Labels: bug, tools

#90 File mapping
  NanoAODProduction/scripts/tzwi-associateDatasets
Labels: tools

#94 tune updatedataset
  NanoAODProduction/scripts/tzwi-updatedataset
Labels: tools

#95 Plotting tool for ttbb dilepton
  NanoAODProduction/data/crosssection/13TeV.yaml
  TopAnalysis/data/grouping/ttbbDilepton.yaml
  TopAnalysis/data/histogramming/ttbbDilepton.yaml
  TopAnalysis/data/plots/ttbbDilepton.yaml
  TopAnalysis/scripts/tzwi-makehistograms
  TopAnalysis/test/fcncTriLepton/02_make_histograms.py
  TopAnalysis/test/ttbarDoubleLepton/02_make_histograms.py
  TopAnalysis/test/ttbarDoubleLepton/03_scalemerge.py
  TopAnalysis/test/ttbarDoubleLepton/04_drawPlots.py
  TopAnalysis/test/ttbarDoubleLepton/config/crosssection.yaml
  TopAnalysis/test/ttbarDoubleLepton/config/datasets/MC.RunIISummer16.central.yaml
  TopAnalysis/test/ttbarDoubleLepton/config/datasets/MC.RunIISummer16.rareprocess.yaml
  TopAnalysis/test/ttbarDoubleLepton/config/datasets/MC.RunIISummer16.syst.yaml
  TopAnalysis/test/ttbarDoubleLepton/config/datasets/RD.Run2016.yaml
  TopAnalysis/test/ttbarDoubleLepton/config/grouping.yaml
  TopAnalysis/test/ttbarDoubleLepton/config/histogramming.yaml
  TopAnalysis/test/ttbarDoubleLepton/config/plots.yaml
  TopAnalysis/test/ttbarDoubleLepton/config/systematics.yaml
Labels: analysis, postprocessor

#97 Plotting bugfix
  TopAnalysis/test/ttbarDoubleLepton/03_scalemerge.py
  TopAnalysis/test/ttbarDoubleLepton/04_drawPlots.py
Labels: analysis, bug

#98 Common plotting
  TopAnalysis/data/combineHLT/ttbarDoubleLepton/2016.yaml
  TopAnalysis/data/combineHLT/ttbarDoubleLepton/2017.yaml
  TopAnalysis/python/postprocessing/ttbarDoubleLeptonHLT.py
  TopAnalysis/test/common/03_scalemerge.py
  TopAnalysis/test/common/04_drawPlots.py
  TopAnalysis/test/fcncTriLepton/03_scalemerge.py
  TopAnalysis/test/fcncTriLepton/04_drawPlots.py
  TopAnalysis/test/ttbarDoubleLepton/01_prod_ntuple.sh
  TopAnalysis/test/ttbarDoubleLepton/03_scalemerge.py
  TopAnalysis/test/ttbarDoubleLepton/04_drawPlots.py
Labels: analysis, bug, postprocessor

#99 Job submission tools, process names
  NanoAODProduction/data/crosssection/13TeV.yaml
  NanoAODProduction/data/datasets/NanoAOD/2016/MC.RunIISummer16.central.yaml
  NanoAODProduction/data/datasets/NanoAOD/2016/MC.RunIISummer16.syst.yaml
  TopAnalysis/data/grouping/fcncTrilepton.yaml
  TopAnalysis/test/common/01.2_checkFailed.sh
  TopAnalysis/test/common/03_scalemerge.py
  TopAnalysis/test/fcncTriLepton/01.1_submit.sh
  TopAnalysis/test/fcncTriLepton/01.2_checkFailed.sh
  TopAnalysis/test/ttbarDoubleLepton/01.1_submit.sh
  TopAnalysis/test/ttbarDoubleLepton/01.2_checkFailed.sh
Labels: tools

#100 Technical updates
  NanoAODProduction/data/datasets/NanoAOD/2016/MC.RunIISummer16.central.yaml
  NanoAODProduction/scripts/tzwi-updatedataset
  TopAnalysis/data/combineHLT/ttbarDoubleLepton/2016.yaml
  TopAnalysis/data/grouping/fcncTrilepton.yaml
  TopAnalysis/data/histogramming/fcncTrilepton.yaml
  TopAnalysis/data/histogramming/ttbbDilepton.yaml
  TopAnalysis/test/common/01.2_checkFailed.sh
  TopAnalysis/test/fcncTriLepton/01.1_submit.sh
  TopAnalysis/test/fcncTriLepton/02_make_histograms.py
  TopAnalysis/test/ttbarDoubleLepton/01.1_submit.sh
  TopAnalysis/test/ttbarDoubleLepton/02_make_histograms.py
Labels: NanoAOD-production, postprocessor, tools

#101 Technical changes
  NanoAODProduction/scripts/tzwi-updatedataset
  TopAnalysis/scripts/tzwi-makehistograms
  TopAnalysis/test/common/04_drawPlots.py
Labels: tools

#102 Fix wrong genWeight - missing weight sign
  TopAnalysis/data/grouping/fcncTrilepton.yaml
  TopAnalysis/data/grouping/ttbbDilepton.yaml
Labels: analysis, bug

#103 Reduce duplicated code
  TopAnalysis/test/common/02_make_histograms.py
  TopAnalysis/test/fcncTriLepton/02_make_histograms.py
  TopAnalysis/test/ttbarDoubleLepton/02_make_histograms.py
Labels: tools

#104 Job submittor update
  TopAnalysis/test/fcncTriLepton/01.1_submit.py
  TopAnalysis/test/fcncTriLepton/01.1_submit.sh
  TopAnalysis/test/ttbarDoubleLepton/01.1_submit.py
  TopAnalysis/test/ttbarDoubleLepton/01.1_submit.sh
Labels: tools

#105 submit jobs under a subdirectory, bugfix
  TopAnalysis/test/fcncTriLepton/01.1_submit.py
  TopAnalysis/test/ttbarDoubleLepton/01.1_submit.py
Labels: bug, tools

#106 Single lepton trig, cutstep, diboson dataset, plotting
  NanoAODProduction/data/datasets/NanoAOD/2016/MC.RunIISummer16.central.yaml
  NanoAODProduction/data/datasets/NanoAOD/2016/RD.Run2016.yaml
  TopAnalysis/data/combineHLT/ttbarDoubleLepton/2016.yaml
  TopAnalysis/data/histogramming/ttbbDilepton.yaml
  TopAnalysis/data/plots/ttbbDilepton.yaml
  TopAnalysis/python/postprocessing/ttbarDoubleLeptonCutFlow.py
  TopAnalysis/python/postprocessing/ttbarDoubleLeptonHLT.py
  TopAnalysis/test/ttbarDoubleLepton/01_prod_ntuple.sh
Labels: analysis, postprocessor

#107 Better plotting
  TopAnalysis/data/histogramming/ttbbDilepton.yaml
  TopAnalysis/test/common/04_drawPlots.py
Labels: tools

#108 Plotting bugfix + better styling
  TopAnalysis/data/grouping/ttbbDilepton.yaml
  TopAnalysis/data/plots/ttbbDilepton.yaml
  TopAnalysis/test/common/03_scalemerge.py
  TopAnalysis/test/common/04_drawPlots.py
Labels: analysis, bug

#109 minor fixes for fcnc plotting
  TopAnalysis/scripts/tzwi-makehistograms
  TopAnalysis/test/common/04_drawPlots.py
Labels: bug

#110 plotting update
  NanoAODProduction/data/datasets/NanoAOD/2016/MC.RunIISummer16.central.yaml
  TopAnalysis/data/histogramming/fcncTrilepton.yaml
  TopAnalysis/test/fcncTriLepton/01.1_submit.py
  TopAnalysis/test/ttbarDoubleLepton/01.1_submit.py
Labels: bug

#112 Fix to plotting
  TopAnalysis/data/grouping/fcncTrilepton.yaml
  TopAnalysis/data/grouping/ttbbDilepton.yaml
  TopAnalysis/data/histogramming/fcncTrilepton.yaml
  TopAnalysis/data/plots/fcncTrilepton.yaml
  TopAnalysis/scripts/tzwi-makehistograms
  TopAnalysis/test/common/02_make_histograms.py
  TopAnalysis/test/common/03_scalemerge.py
Labels: analysis, bug, postprocessor

#111 Adding & changing histogramming
  TopAnalysis/data/histogramming/fcncTrilepton.yaml
  TopAnalysis/data/plots/fcncTrilepton.yaml
Labels: analysis
