Repository cms-kr/TZWi, pull requests merged in 2019-03, with the labels that each got.

#18 2016 dataset list
  NanoAODProduction/data/datasets/2016/MC.tsv
  NanoAODProduction/data/datasets/2016/RD_DoubleLepton.tsv
  NanoAODProduction/data/datasets/2016/RD_SingleLepton.tsv
Labels: NanoAOD-production

#16 TFormula based HLT combiner
  TopAnalysis/data/combineHLT/flags/MC_RunIISummer16.json
  TopAnalysis/data/combineHLT/flags/RD_Run2016.json
  TopAnalysis/data/combineHLT/ttbarDoubleLepton/MC_RunIISummer16.json
  TopAnalysis/data/combineHLT/ttbarDoubleLepton/RD_Run2016BG.json
  TopAnalysis/data/combineHLT/ttbarDoubleLepton/RD_Run2016H.json
  TopAnalysis/interface/CombineHLTCppWorker.h
  TopAnalysis/python/CombineHLT.py
  TopAnalysis/python/ttbarDoubleLeptonHLT.py
  TopAnalysis/src/CombineHLTCppWorker.cc
Labels: postprocessor

#21 Update flags and HLT formula for the 2016 dilepton analysis
  TopAnalysis/data/combineHLT/flags/MC_RunIISummer16.json
  TopAnalysis/data/combineHLT/flags/RD_Run2016.json
  TopAnalysis/data/combineHLT/ttbarDoubleLepton/MC_RunIISummer16.json
  TopAnalysis/data/combineHLT/ttbarDoubleLepton/RD_Run2016BG.json
  TopAnalysis/data/combineHLT/ttbarDoubleLepton/RD_Run2016H.json
Labels: postprocessor

#20 2017 Data/MC HLT and flags
  NanoAODProduction/test/crabConfig.py
  TopAnalysis/data/combineHLT/flags/MC_RunIIFall17.json
  TopAnalysis/data/combineHLT/flags/RD_Run2017.json
  TopAnalysis/data/combineHLT/ttbarDoubleLepton/MC_RunIIFall17.json
  TopAnalysis/data/combineHLT/ttbarDoubleLepton/RD_Run2017B.json
  TopAnalysis/data/combineHLT/ttbarDoubleLepton/RD_Run2017CF.json
  TopAnalysis/python/ttbarDoubleLeptonHLT.py
Labels: postprocessor

#23 bugfix: missing era arguments in cmsDriver.py
  NanoAODProduction/test/generateConfig.sh
Labels: NanoAOD-production, bug

#24 Bugfix crashing CombineHLT
  TopAnalysis/interface/CombineHLTCppWorker.h
  TopAnalysis/python/CombineHLT.py
  TopAnalysis/src/CombineHLTCppWorker.cc
Labels: bug, postprocessor

#25 PartonTopPostProcessor uses framework supported branch
  README.md
  TopAnalysis/interface/PartonTopCppWorker.h
  TopAnalysis/python/partonTop.py
  TopAnalysis/src/PartonTopCppWorker.cc
  TopAnalysis/test/prod_ntuple/run.sh
Labels: bug, postprocessor

#27 Trilepton worker update
  TopAnalysis/interface/FCNCTriLeptonCppWorker.h
  TopAnalysis/src/FCNCTriLeptonCppWorker.cc
Labels: postprocessor

#28 FCNC postprocessor update
  TopAnalysis/interface/FCNCTriLeptonCppWorker.h
  TopAnalysis/python/fcncTriLepton.py
  TopAnalysis/src/FCNCTriLeptonCppWorker.cc
  TopAnalysis/test/fcncTriLepton/.gitignore
  TopAnalysis/test/fcncTriLepton/prod_ntuple/run.sh
  TopAnalysis/test/ttbarDoubleLepton/.gitignore
  TopAnalysis/test/ttbarDoubleLepton/prod_ntuple/run.sh
  TopAnalysis/test/ttbarDoubleLepton/prod_ntuple/submitCondor.py
Labels: postprocessor

#22 Match branch name, add lepSF, PUweight
  TopAnalysis/interface/TTbarDoubleLeptonCppWorker.h
  TopAnalysis/python/ttbarDoubleLepton.py
  TopAnalysis/python/ttbarDoubleLeptonHLT.py
  TopAnalysis/src/TTbarDoubleLeptonCppWorker.cc
  TopAnalysis/test/ttbarDoubleLepton/prod_ntuple/run.sh
Labels: postprocessor

#26 Dilepton postprocessor to use framework branch output
  TopAnalysis/interface/TTbarDoubleLeptonCppWorker.h
  TopAnalysis/python/ttbarDoubleLepton.py
  TopAnalysis/src/TTbarDoubleLeptonCppWorker.cc
Labels: pending, postprocessor

#29 Additional fixes to use framework supported output
  TopAnalysis/interface/TTbarDoubleLeptonCppWorker.h
  TopAnalysis/python/ttbarDoubleLepton.py
  TopAnalysis/test/fcncTriLepton/prod_ntuple/run.sh
  TopAnalysis/test/ttbarDoubleLepton/prod_ntuple/run.sh
Labels: bug, postprocessor

#30 Do not separate SF branches from the "reco" ntuple
  TopAnalysis/test/fcncTriLepton/prod_ntuple/run.sh
  TopAnalysis/test/ttbarDoubleLepton/prod_ntuple/run.sh
Labels: postprocessor

#31 Redo code changes
  TopAnalysis/interface/TTbarDoubleLeptonCppWorker.h
  TopAnalysis/python/ttbarDoubleLepton.py
  TopAnalysis/src/TTbarDoubleLeptonCppWorker.cc
  TopAnalysis/test/fcncTriLepton/prod_ntuple/run.sh
  TopAnalysis/test/ttbarDoubleLepton/prod_ntuple/run.sh
Labels: bug, postprocessor

#32 Fix typo on flag and HLT
  TopAnalysis/data/combineHLT/flags/MC_RunIIFall17.json
  TopAnalysis/data/combineHLT/flags/RD_Run2017.json
  TopAnalysis/python/ttbarDoubleLeptonHLT.py
Labels: bug, postprocessor

#34 Update MC.tsv space to tab.
  NanoAODProduction/data/datasets/2016/MC.tsv
Labels: NanoAOD-production

#35 Framework supported tree booking and filling
  TopAnalysis/interface/FCNCTriLeptonCppWorker.h
  TopAnalysis/interface/TTbarDoubleLeptonCppWorker.h
  TopAnalysis/python/fcncTriLepton.py
  TopAnalysis/src/FCNCTriLeptonCppWorker.cc
  TopAnalysis/src/TTbarDoubleLeptonCppWorker.cc
Labels: postprocessor

#33 modified config script (difference of Global Tag)
  NanoAODProduction/test/generateConfig.sh
Labels: NanoAOD-production, bug

#36 Cut Flow analyzer in a separate postprocessor
  TopAnalysis/interface/FCNCTriLeptonCppWorker.h
  TopAnalysis/interface/TTbarDoubleLeptonCppWorker.h
  TopAnalysis/python/fcncTriLepton.py
  TopAnalysis/python/fcncTriLeptonCutFlow.py
  TopAnalysis/python/ttbarDoubleLepton.py
  TopAnalysis/python/ttbarDoubleLeptonCutFlow.py
  TopAnalysis/python/ttbarDoubleLeptonHLT.py
  TopAnalysis/src/FCNCTriLeptonCppWorker.cc
  TopAnalysis/src/TTbarDoubleLeptonCppWorker.cc
  TopAnalysis/test/fcncTriLepton/prod_ntuple/run.sh
  TopAnalysis/test/ttbarDoubleLepton/prod_ntuple/run.sh
Labels: bug, postprocessor

#37 Separate postproc migration
  TopAnalysis/python/fcncTriLeptonCutFlow.py
  TopAnalysis/src/FCNCTriLeptonCppWorker.cc
  TopAnalysis/test/fcncTriLepton/prod_ntuple/run.sh
Labels: bug, postprocessor

#39 YAML based HLT config, support multiple HLT flag types, bugfix
  TopAnalysis/data/combineHLT/FCNCTrilepton/MC_RunIISummer16.json
  TopAnalysis/data/combineHLT/FCNCTrilepton/RD_Run2016BH.json
  TopAnalysis/data/combineHLT/fcncTriLepton/2016.yaml
  TopAnalysis/data/combineHLT/flags/2016.yaml
  TopAnalysis/data/combineHLT/flags/2017.yaml
  TopAnalysis/data/combineHLT/flags/MC_RunIIFall17.json
  TopAnalysis/data/combineHLT/flags/MC_RunIISummer16.json
  TopAnalysis/data/combineHLT/flags/RD_Run2016.json
  TopAnalysis/data/combineHLT/flags/RD_Run2017.json
  TopAnalysis/data/combineHLT/ttbarDoubleLepton/2016.yaml
  TopAnalysis/data/combineHLT/ttbarDoubleLepton/2017.yaml
  TopAnalysis/data/combineHLT/ttbarDoubleLepton/MC_RunIIFall17.json
  TopAnalysis/data/combineHLT/ttbarDoubleLepton/MC_RunIISummer16.json
  TopAnalysis/data/combineHLT/ttbarDoubleLepton/RD_Run2016BG.json
  TopAnalysis/data/combineHLT/ttbarDoubleLepton/RD_Run2016H.json
  TopAnalysis/data/combineHLT/ttbarDoubleLepton/RD_Run2017B.json
  TopAnalysis/data/combineHLT/ttbarDoubleLepton/RD_Run2017CF.json
  TopAnalysis/interface/CombineHLTCppWorker.h
  TopAnalysis/python/CombineHLT.py
  TopAnalysis/python/fcncTriLeptonHLT.py
  TopAnalysis/python/ttbarDoubleLeptonHLT.py
  TopAnalysis/src/CombineHLTCppWorker.cc
  TopAnalysis/test/fcncTriLepton/prod_ntuple/run.sh
  TopAnalysis/test/ttbarDoubleLepton/prod_ntuple/run.sh
Labels: bug, postprocessor

#38 update the 2016 MC signal sample location
  NanoAODProduction/data/datasets/2016/MC.tsv
  NanoAODProduction/data/datasets/2016/MC_signal.tsv
Labels: NanoAOD-production

#41 protection from flipped channel input
  TopAnalysis/test/fcncTriLepton/prod_ntuple/run.sh
  TopAnalysis/test/ttbarDoubleLepton/prod_ntuple/run.sh
Labels: postprocessor

#42 bugfix select by lepton multiplicity, wrong index
  TopAnalysis/src/FCNCTriLeptonCppWorker.cc
Labels: bug, postprocessor

#40 Sample list with yaml format
  NanoAODProduction/data/datasets/2016/MC.tsv
  NanoAODProduction/data/datasets/2016/MC_signal.tsv
  NanoAODProduction/data/datasets/2016/RD_DoubleLepton.tsv
  NanoAODProduction/data/datasets/2016/RD_SingleLepton.tsv
  NanoAODProduction/data/datasets/2017/MC.tsv
  NanoAODProduction/data/datasets/2017/RD_DoubleLepton.tsv
  NanoAODProduction/data/datasets/2017/RD_SingleLepton.tsv
  NanoAODProduction/data/datasets/MiniAOD/2016/MC.RunIISummer16.central.yaml
  NanoAODProduction/data/datasets/MiniAOD/2016/MC.RunIISummer16.rareprocess.yaml
  NanoAODProduction/data/datasets/MiniAOD/2016/MC.RunIISummer16.syst.yaml
  NanoAODProduction/data/datasets/MiniAOD/2016/RD.Run2016.yaml
  NanoAODProduction/data/datasets/MiniAOD/2017/RD.Run2017.yaml
  NanoAODProduction/data/datasets/NanoAOD/2016/MC.RunIISummer16.central.yaml
  NanoAODProduction/data/datasets/NanoAOD/2016/MC.RunIISummer16.rareprocess.yaml
  NanoAODProduction/data/datasets/NanoAOD/2016/MC.RunIISummer16.syst.yaml
  NanoAODProduction/data/datasets/NanoAOD/2016/RD.Run2016.yaml
  NanoAODProduction/data/datasets/NanoAOD/2017/RD.Run2017.yaml
Labels: NanoAOD-production

#43 change yaml structure for NanoAOD
  NanoAODProduction/data/datasets/MiniAOD/2016/MC.RunIISummer16.central.yaml
  NanoAODProduction/data/datasets/NanoAOD/2016/RD.Run2016.yaml
  NanoAODProduction/data/datasets/NanoAOD/2017/RD.Run2017.yaml
Labels: NanoAOD-production

#45 2016 MC sample list update from tsv
  NanoAODProduction/data/datasets/NanoAOD/2016/MC.RunIISummer16.central.yaml
  NanoAODProduction/data/datasets/NanoAOD/2016/MC.RunIISummer16.rareprocess.yaml
  NanoAODProduction/data/datasets/NanoAOD/2016/MC.RunIISummer16.syst.yaml
Labels: NanoAOD-production

#44 Add 2017 Dataset list as yaml format
  NanoAODProduction/data/datasets/NanoAOD/2017/RD.Run2017.yaml
  TopAnalysis/python/ttbarDoubleLeptonCutFlow.py
Labels: NanoAOD-production, postprocessor

#46 Add btagSF postproc, fix puweight to use 2017
  TopAnalysis/test/ttbarDoubleLepton/prod_ntuple/run.sh
Labels: postprocessor

#47 bugfix in 'CombineHLT.py' & change 'run.sh' in trilepton channel
  TopAnalysis/data/combineHLT/fcncTriLepton/2016.yaml
  TopAnalysis/python/CombineHLT.py
  TopAnalysis/python/fcncTriLeptonHLT.py
  TopAnalysis/test/fcncTriLepton/prod_ntuple/run.sh
Labels: bug, postprocessor

#48 bugfix calling tight id
  TopAnalysis/src/FCNCTriLeptonCppWorker.cc
Labels: bug, postprocessor

#49 Changing the Electron cutbased id
  TopAnalysis/python/fcncTriLepton.py
  TopAnalysis/test/fcncTriLepton/prod_ntuple/run.sh
Labels: postprocessor

#50 BtagWeight producer, better inter-module object handling
  TopAnalysis/interface/FCNCTriLeptonCppWorker.h
  TopAnalysis/interface/TTbarDoubleLeptonCppWorker.h
  TopAnalysis/python/btagWeightProducer.py
  TopAnalysis/python/fcncTriLepton.py
  TopAnalysis/python/fcncTriLeptonCutFlow.py
  TopAnalysis/python/ttbarDoubleLepton.py
  TopAnalysis/python/ttbarDoubleLeptonCutFlow.py
  TopAnalysis/src/FCNCTriLeptonCppWorker.cc
  TopAnalysis/src/TTbarDoubleLeptonCppWorker.cc
  TopAnalysis/test/fcncTriLepton/prod_ntuple/run.sh
  TopAnalysis/test/ttbarDoubleLepton/prod_ntuple/run.sh
Labels: postprocessor

#51 output directory
  TopAnalysis/test/ttbarDoubleLepton/prod_ntuple/run.sh
Labels: postprocessor

#58 Branch copying postprocessor
  TopAnalysis/python/CombineHLT.py
  TopAnalysis/python/CopyBranch.py
  TopAnalysis/python/btagWeightProducer.py
  TopAnalysis/python/fcncTriLepton.py
  TopAnalysis/python/fcncTriLeptonHLT.py
  TopAnalysis/python/ttbarDoubleLeptonCutFlow.py
  TopAnalysis/python/ttbarDoubleLeptonHLT.py
  TopAnalysis/test/fcncTriLepton/prod_ntuple/run.sh
  TopAnalysis/test/ttbarDoubleLepton/prod_ntuple/run.sh
Labels: postprocessor

#59 New script to list up available nanoAOD files
  NanoAODProduction/data/datasets/NanoAOD/2016/MC.RunIISummer16.central.yaml
  NanoAODProduction/data/datasets/NanoAOD/2016/MC.RunIISummer16.rareprocess.yaml
  NanoAODProduction/data/datasets/NanoAOD/2016/RD.Run2016.yaml
  NanoAODProduction/data/datasets/NanoAOD/2017/RD.Run2017.yaml
  NanoAODProduction/scripts/tzwi-udpatedataset
Labels: tools

#62 added new histogramming step
  TopAnalysis/data/combineHLT/ttbarDoubleLepton/2017.yaml
  TopAnalysis/data/histogramming/fcncTrilepton.yaml
  TopAnalysis/data/histogramming/ttbbDilepton.yaml
  TopAnalysis/scripts/tzwi-makehistograms
  TopAnalysis/test/fcncTriLepton/01_prod_ntuple.sh
  TopAnalysis/test/fcncTriLepton/02_make_histograms.sh
  TopAnalysis/test/fcncTriLepton/NanoAOD
  TopAnalysis/test/ttbarDoubleLepton/01_prod_ntuple.sh
  TopAnalysis/test/ttbarDoubleLepton/02_make_histograms.sh
  TopAnalysis/test/ttbarDoubleLepton/NanoAOD
Labels: analysis, bug, postprocessor, tools

#65 Non-crashing histogramming step
  TopAnalysis/data/histogramming/ttbbDilepton.yaml
  TopAnalysis/scripts/tzwi-makehistograms
  TopAnalysis/test/ttbarDoubleLepton/02_make_histograms.sh
Labels: analysis

#66 fix typo
  NanoAODProduction/data/datasets/NanoAOD/2016/MC.RunIISummer16.syst.yaml
  NanoAODProduction/scripts/tzwi-updatedataset
Labels: NanoAOD-production
