Repository cms-kr/TZWi, pull requests merged in 2020-01, with the labels that each got.

#136 Adding the omission thing & modifying the NPL logic
  NanoAODProduction/data/crosssection/13TeV.yaml
  NanoAODProduction/data/datasets/NanoAOD/2016/MC.RunIISummer16.central.yaml
  TopAnalysis/data/grouping/fcncTrilepton.yaml
  TopAnalysis/data/histogramming/fcncTrilepton.yaml
  TopAnalysis/data/plots/fcncTrilepton.yaml
  TopAnalysis/interface/FCNCTriLeptonCppWorker.h
  TopAnalysis/python/postprocessing/fcncTriLepton.py
  TopAnalysis/python/postprocessing/fcncTriLeptonCutFlow.py
  TopAnalysis/src/FCNCTriLeptonCppWorker.cc
Labels: postprocessor

#141 Lepton scale factor apply & fix direction & fcncCutFlow.py typo fix
  TopAnalysis/data/leptonSF/EGM2D_eleGSF.root
  TopAnalysis/data/leptonSF/EGM2D_eleMVA90.root
  TopAnalysis/data/leptonSF/Mu_ID.root
  TopAnalysis/data/leptonSF/Mu_ID_2016BCDEF.root
  TopAnalysis/data/leptonSF/Mu_ID_2016GH.root
  TopAnalysis/data/leptonSF/Mu_ISO_2016BCDEF.root
  TopAnalysis/data/leptonSF/Mu_ISO_2016GH.root
  TopAnalysis/data/leptonSF/Mu_Iso.root
  TopAnalysis/data/leptonSF/Mu_Trg.root
  TopAnalysis/data/leptonSF/Mu_Trig_2016BCDEF.root
  TopAnalysis/data/leptonSF/Mu_Trig_2016GH.root
  TopAnalysis/data/leptonSF/TightWP_2016.root
  TopAnalysis/python/postprocessing/fcncTriLeptonCutFlow.py
  TopAnalysis/python/postprocessing/helpers/LeptonEfficiencyCorrector.cc
  TopAnalysis/python/postprocessing/lepSFProducer.py
  TopAnalysis/test/fcncTriLepton/01_prod_ntuple.sh
Labels: postprocessor

#142 Update branchsel
  NanoAODProduction/data/branchsel.txt
  README.md
Labels: postprocessor

#145 ttbar dilepton bugfix
  TopAnalysis/src/TTbarDoubleLeptonCppWorker.cc
  TopAnalysis/test/common/01.2_checkFailed.sh
  TopAnalysis/test/ttbarDoubleLepton/01_prod_ntuple.sh
Labels: bug, postprocessor

#146 new URL for the kisti T2 storage
  NanoAODProduction/scripts/tzwi-updatedataset
Labels: tools
